# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: init_pose
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
    sim_control_mode: 0

# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  #gains:
  #  joint1: {p: 1.0, d: 50.0, i: 0.0, i_clamp: 1}
  #  joint2: {p: 1.0, d: 50.0, i: 0.0, i_clamp: 1}
  #  joint3: {p: 1.0, d: 50.0, i: 0.0, i_clamp: 1}
  #  joint4: {p: 1.0, d: 50.0, i: 0.0, i_clamp: 1}
  #velocity_ff:
  #    joint1: 1.0
  #    joint2: 1.0
  #    joint3: 1.0
  #    joint4: 1.0

  constraints: 
    goal_time: 2.0
  state_publish_rate: 50

controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4